name: Windows-CRD1px

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: acessando o diretorio dos arquivos
      run: |
       cd D:\a\Windows-CRD1px\Windows-CRD1px
    - name: start ps1 for setup
      run: wget https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi
    - name: start chromeremotedesktophost.msi
      run: start chromeremotedesktophost.msi
    - name: Esperar o msi fechar
      run: timeout 30
      
    - name: Starting CRD
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: start timeout.ps1
