name: Windows-CRD1px

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: acessando o diretorio dos arquivos
      run: |
       cd D:\a\Windows-CRD1px\Windows-CRD1px
    - name: start ps1 for setup
      run: curl -o chromeremotedesktophost.msi https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi
    - name: start chromeremotedesktop.msi
      run: start chromeremotedesktophost.msi
    - name: create .bat for timeout
      run: echo timeout 30 | exit >> timeout.bat
    - name: timeout
      run: cmd timeout.bat
    - name: cd chromeremotedesktop
      run: cd "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion"
    - name: Starting CRD
      run: remoting_start_host.exe --code="4/0AdLIrYdfZsStcuy6mK5WU908pc0XSUymxgsrWiymLcujXkGVJzJwix415HwzCjvSeGBeJQ" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin 123456
    - name: Keep Alive
      run: cmd timeout 21600
