name: Windows-CRD1px

on: 
  workflow_dispatch:
    inputs:
      authcode:
        description: 'Enter CRD code'
        required: true
      pincode:
        description: 'Six digit Pin'
        required: true
  
jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: acessando o diretorio dos arquivos
      run: |
       cd D:\a\Windows-CRD1px\Windows-CRD1px
    - name: start ps1 for setup
      run: curl -o chromeremotedesktophost.msi https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi
    - name: start chromeremotedesktop.msi
      run: start chromeremotedesktophost.msi
    - name: start .bat
      run: cmd
    - name: create timeout.bat & timeout
      run: echo timeout 30 >> timeout.bat
    - name: start 2 .bat
      run: timeout 30
    - name: cd chromeremotedesktop
      run: cd "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion"
    - name: Starting CRD
      run: remoting_start_host.exe --code="4/0AdLIrYd317OF9YDZtKFheBVVNZ82RSnsrt8VeRweA9lmnfuQM6-82wIzC707UXg2qQZ75w" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME
    - name: Keep Alive
      run: cmd timeout 21600
